### ISSUE TITLE
TODO Before We Can Enabling Robot

### ISSUE THREAD

**Issue by LuminousLlama** [FRC-Sonic-Squirrels/2023-Robot-Code#54]
- [x] CANivore: update firmware and set name to "CANivore"
- [x] roboRIO, image SD card with latest image (done 2/11/2023)
- [x] roboRIO: set team number, check firmware
- [x] Rev products, update firmware: PDP
- [x] set CAN ids on all motors and devices (use Constants.java as a guild)
- [x] Swerve: record encoder offsets and add to Constants.java for 2023 comp bot
- [x] insert USB thumbdrive for recording WPILogs (2/11/2023)
- [x] FIXME: set the CANivore name on 2023 robot to "CANivore"  (is currently "CANivor" with no "e")
- [x] test flipped swerve drive motors (back left drive, back right steer)
- [x] confirm elevator limit switch works, display on dashboard
- [x] confirm stinger limit switch works, display on dashboard
- [x] manually move elevator up/down and confirm elevator height in code on SmartDashboard
- [x] manually move stinger in/out and confirm extention in code on SmartDashboard

Record the date an firmware numbers in the comments when you update a device.
