### ISSUE TITLE
TODO testing after enabling robot 

### ISSUE THREAD

**Issue by LuminousLlama** [FRC-Sonic-Squirrels/2023-Robot-Code#56]
**Drivetrain** 
- [x] test mk4i- code (put robot on wooden stilts and confirm every module is spinning the same way) 
- [ ] characterize drivetrain (might be worth doing this on the 2022 robot for practice) 
- [x] put characterized constants into code 
- [x] run test auto paths on robot (2m forward) (2m forward 180) etc. etc. 

**Elevator** 
- [x] test lower limit switch and upper soft limit
- [x] test/calibrate ticks2distance
- [x] find voltage that holds the elevator in one position (empty, with cube, with cone)
- [x] tune PID (kP) for simple positional control
- [ ] tune kI and iZone ( = 0.5-1")
- [x] confirm trapezoidal motion is working

**Stinger**
- [x] test setExtension and manualControl (does it go to desired position?)
- [x] test upper and lower limit switches
- [x] make sure the ticks2distance calculation is accurate to the real stinger
- [x] tune the PID numbers for more stable stinger control
- [x] see whether or not the motor must be inverted (unless we already know this)

**intake**
- [x] note direction of motor for intake/outake of cubes/cones and update code
- [x] pick intake/outtake Voltage for cubes/cones

**vision**
- [ ] calibrate vision whilst april tags are on the robot 
- [ ] log ambiguity while moving towards, adjacent, and away from the april tag
- [x] test accuracy with the april tags
- [x] odometry using april tags

**LED subsystem (blinkin)**

 - [x] confirm LEDs work
 - [x] trigger purple/yellow/orange/"black"

**Stingevator Setpoints and Commands**

- [x] High/Mid/low cube scoring position
- [x] High/Mid/Low cone scoring position
- [x] ground pickup cube/cone
- [x] stow position cube/cone
- [ ] Commands for each position (command factory) with and without scoring to allow for manual trigger

**Bumpers**

- [x] attach bumpers check fit
- [x] test driving onto charge station
