### ISSUE TITLE
TODO things to test at practice field

### ISSUE THREAD

**Issue by CodeCreator3** [FRC-Sonic-Squirrels/2023-Robot-Code#58]
High Priority
- [x] test position estimation accuracy with april tags (blue and red sides)
- [x] manual pickup (ground and substation)
- [x] manual scoring
- [x] manual charge pad engaging

Mid Priority
- [x] test auto paths (possibly without events at first) (blue and red sides)
- [ ] auto drive to grid pos and score (with stream deck)
- [ ] auto pickup from substations (Cubes and Cones)

Low Priority
- [ ] do auto pickup, then autoscore to get a rough average cycle time
- [ ] optimize auto paths
