### ISSUE TITLE
TODO: things we have left to do

### ISSUE THREAD

**Issue by CodeCreator3** [FRC-Sonic-Squirrels/2023-Robot-Code#65]
- [x] faster "stingevator" (speed up pace) (test parallel motion)
- [x] install latest DriverStation https://www.ni.com/en-us/support/downloads/drivers/download.frc-game-tools.html#479842
- [x] Photonvision OrangePi Update
- [x] PV calibrate in Gym lighting
- [x] ROCK SOLID mid engage auto (TEST FOR RED ALLIANCE)
- [x] test human player autos for red side
- [x] april tag tuning (new camera mounts)
    - [x] new camera mount just 35 degrees out
    - [ ] ~~decrease FPS on camera~~
    - [x] decrease exposure for gym
- [x] Button for ground pickup while held (toggle for desired game piece)
- [x] bind button for drive set rotation
- [ ] Drive to grid position and score
- [ ] stream deck
- [x] auto substation pickup
- [x] Wall side autos
- [x] pickup game piece in middle engage
- [ ] 3 ball autos
- [ ] 4 ball autos
