### ISSUE TITLE
TODO: practice field 3/11

### ISSUE THREAD

**Issue by CodeCreator3** [FRC-Sonic-Squirrels/2023-Robot-Code#69]
- [x] align swerve
- [x] system test
   - [x] can
   - [x] elevator
   - [x] stinger
   - [x] drive
   - [x] intake
- [x] confirm oper and drive controls
- [ ] SYSID: characterize drivetrain
- [x] test autos
   - [x] 2 meters
   - [x] 2 meters 360
   - [x] simple middle engage +taxi
- [ ] drive to grid position
- [ ] up vision decimate
- [ ] investigate not picking up cubes
- [ ] tune intake stalling
