### ISSUE TITLE
TODO: before DCMP

### ISSUE THREAD

**Issue by CodeCreator3** [FRC-Sonic-Squirrels/2023-Robot-Code#70]
- [x] fix cube alignment with 2 piece engage (possibly switch to purely odometry based auto?)
- [x] make cube ground pickup better
- [x] make drive to grid reliable
- [ ] stream deck integration/testing
- [x] wall side 2 piece engage
- [ ] optimizing current autos (maybe try for 2.5 piece engage auto)
    - [x] tune when stingevator comes up and down to be more in parallel with driving
    - [ ] make stinger extend further for ground pickup
    - [x] see if overall speed/acceleration can be increased?
    - [x] score at end of path, rather then in between paths to make motion more of a "dunk"
- [x] optimizing double substation intaking
   - [x] parallel stingevator drivetrain action
   - [x] tune speed
   - [x] possibly automate driving last couple feet
- [x] optimizing drive to grid and score
   - [x] more parallel stingevator driving
   - [x] try to recreate "dunk" method of scoring
   - [x] tune speed
   - [x] bring final drive in point (to score) closer to actual grid
- [x] PNP vision processing
- [x] make 3 piece autos more reliable
- [ ] middle 1.5 engage
- [x] 3rd camera programming (if mechanical is able to implement)
- [ ] maybe make middle score, cross charge pad, then intake cube, then go around pad to score (compliment other engaging bot)
- [x] adjust low translation elevator height, slowed down speed, and when elevator is going down don't slow robot 
- [x] adjust elevator stow height so cubes picked up from the ground don't fall out from hitting the bumper 
- [x] test cube pickup from double feeder station
- [x] investigate cone pickup from single substation (254 style)
